import { FormEvent, useMemo, useState } from 'react';
import './styles.css';

export type Summary = { name: string; count: number; color: string };
export type Role = 'Ward recorder' | 'Provincial supervisor' | 'Provincial administrator' | 'National viewer';
export type Hazard = 'Flood' | 'Drought' | 'Fire' | 'Zoonotic disease' | 'Mining accident';
export type Status = 'PENDING' | 'APPROVED' | 'REJECTED' | 'CORRECTION_REQUESTED';
export type Incident = { id: string; hazard: Hazard; ward: string; district: string; occurredAt: string; severity: string; latitude: number; longitude: number; status: Status; reporter: string; fields: Record<string, string>; audit: Audit[] };
export type Audit = { at: string; actor: string; action: string; reason?: string };
export type Session = { name: string; role: Role; hazard: Hazard; ward: string };

export const hazards: Hazard[] = ['Flood', 'Drought', 'Fire', 'Zoonotic disease', 'Mining accident'];
export const colors: Record<Hazard, string> = { Flood: '#0ea5e9', Drought: '#f59e0b', Fire: '#ef4444', 'Zoonotic disease': '#8b5cf6', 'Mining accident': '#64748b' };
export const indicators: Record<Hazard, [string, string][]> = {
  Flood: [['peakWaterLevelMetres', 'Peak water level (metres)'], ['riverBasin', 'River basin / catchment'], ['householdsDisplaced', 'Households displaced'], ['floodedAreaHectares', 'Area flooded (hectares)'], ['inundationDays', 'Inundation duration (days)']],
  Drought: [['rainfallDeficitMm', 'Rainfall deficit (mm)'], ['consecutiveDryDays', 'Consecutive dry days'], ['cropFailurePercent', 'Crop failure (%)'], ['peopleWaterShortage', 'People facing water shortages'], ['livestockMortality', 'Livestock mortality count']],
  Fire: [['areaBurnedHectares', 'Area burned (hectares)'], ['suspectedCause', 'Suspected cause'], ['casualties', 'Injuries / fatalities'], ['structuresDestroyed', 'Structures destroyed'], ['fireState', 'Still active or contained']],
  'Zoonotic disease': [['pathogen', 'Pathogen / disease'], ['animalSpecies', 'Animal species affected'], ['humanCases', 'Confirmed human cases'], ['animalCases', 'Confirmed animal cases'], ['classification', 'Cluster or outbreak']],
  'Mining accident': [['mineNameAndType', 'Mine name and type'], ['accidentType', 'Accident type'], ['trappedOrInjured', 'Trapped / injured miners'], ['fatalities', 'Fatalities'], ['rescueStatus', 'Rescue operations status']],
};

export const load = <T,>(key: string, fallback: T): T => { try { return JSON.parse(localStorage.getItem(key) ?? '') as T; } catch { return fallback; } };
export const store = (key: string, value: unknown) => localStorage.setItem(key, JSON.stringify(value));

export function App() {
  const [session, setSession] = useState<Session | null>(() => load<Session | null>('dpdms-session', null));
  const [incidents, setIncidents] = useState<Incident[]>(() => load<Incident[]>('dpdms-incidents', []));
  const [showSignIn, setShowSignIn] = useState(false); const [editing, setEditing] = useState<Incident | null>(null); const [tab, setTab] = useState<'dashboard' | 'record' | 'my-incidents' | 'review' | 'reports' | 'alerts'>('dashboard');
  const [name, setName] = useState(''); const [role, setRole] = useState<Role>('Ward recorder'); const [assignedHazard, setAssignedHazard] = useState<Hazard>('Flood'); const [ward, setWard] = useState('Ward 1'); const [message, setMessage] = useState('');
  const [filter, setFilter] = useState<Hazard | 'All'>('All'); const approved = incidents.filter(x => x.status === 'APPROVED');
  const summaries: Summary[] = hazards.map(h => ({ name: `${h}s`, count: approved.filter(x => x.hazard === h).length, color: colors[h] }));
  const alerts = useMemo(() => incidents.filter(x => x.status === 'APPROVED' && (x.severity === 'CRITICAL' || (x.hazard === 'Flood' && Number(x.fields.peakWaterLevelMetres) >= 3) || (x.hazard === 'Fire' && x.fields.fireState?.toLowerCase().includes('active')))), [incidents]);

  function persist(next: Incident[]) { setIncidents(next); store('dpdms-incidents', next); }
  function signIn(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const next = { name: name.trim(), role, hazard: assignedHazard, ward }; if (!next.name) return; store('dpdms-session', next); setSession(next); setShowSignIn(false); setMessage(`Signed in as ${next.role}.`); }
  function signOut() { localStorage.removeItem('dpdms-session'); setSession(null); setEditing(null); setMessage(''); setTab('dashboard'); }
  function submitIncident(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!session || session.role !== 'Ward recorder') return; const data = new FormData(event.currentTarget); const fields = Object.fromEntries(indicators[session.hazard].map(([key]) => [key, String(data.get(key) ?? '')])); if (editing) { persist(incidents.map(x => x.id === editing.id ? { ...x, district: String(data.get('district')), occurredAt: String(data.get('occurredAt')), severity: String(data.get('severity')), latitude: Number(data.get('latitude')), longitude: Number(data.get('longitude')), status: 'PENDING', fields, audit: [...x.audit, { at: new Date().toISOString(), actor: session.name, action: 'Corrected and resubmitted' }] } : x)); setEditing(null); setMessage('Corrections saved and the incident has been resubmitted.'); } else { const incident: Incident = { id: crypto.randomUUID(), hazard: session.hazard, ward: session.ward, district: String(data.get('district')), occurredAt: String(data.get('occurredAt')), severity: String(data.get('severity')), latitude: Number(data.get('latitude')), longitude: Number(data.get('longitude')), status: 'PENDING', reporter: session.name, fields, audit: [{ at: new Date().toISOString(), actor: session.name, action: 'Submitted for approval' }] }; persist([incident, ...incidents]); setMessage('Incident submitted to the relevant provincial supervisor.'); } setTab('my-incidents'); }
  function decide(id: string, status: Status, reason: string) { if (!session) return; const decisionReason = reason.trim() || (status === 'APPROVED' ? 'Approved for publication' : 'No reason supplied'); persist(incidents.map(x => x.id === id ? { ...x, status, audit: [...x.audit, { at: new Date().toISOString(), actor: session.name, action: status, reason: decisionReason }] } : x)); setMessage(`Incident ${status.toLowerCase().replace('_', ' ')}.`); }
  function exportCsv() { const rows = approved.filter(x => filter === 'All' || x.hazard === filter).map(x => [x.id, x.hazard, x.ward, x.district, x.occurredAt, x.severity, x.latitude, x.longitude, ...Object.values(x.fields)]); const csv = [['id', 'hazard', 'ward', 'district', 'occurred at', 'severity', 'latitude', 'longitude'], ...rows].map(row => row.map(v => `"${String(v).replaceAll('"', '""')}"`).join(',')).join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); link.download = 'dpdms-approved-incidents.csv'; link.click(); URL.revokeObjectURL(link.href); }
  const canRecord = session?.role === 'Ward recorder'; const canReview = session && ['Provincial supervisor', 'Provincial administrator'].includes(session.role);
  const reviewable = incidents.filter(x => x.status === 'PENDING' && (session?.role === 'Provincial administrator' || x.hazard === session?.hazard));
  function edit(incident: Incident) { setEditing(incident); setTab('record'); }
  function remove(id: string) { if (window.confirm('Delete this pending incident? This cannot be undone.')) { persist(incidents.filter(x => x.id !== id)); setMessage('Pending incident deleted.'); } }

  return <main><header><div><small>RUSHINGA PROVINCIAL</small><h1>Disaster Monitoring</h1></div>{session ? <div className="account"><span>{session.name} · {session.role}</span><button className="secondary" onClick={signOut}>Sign out</button></div> : <button onClick={() => setShowSignIn(true)}>Sign in</button>}</header>{session && <nav>{(['dashboard', 'record', 'my-incidents', 'review', 'reports', 'alerts'] as const).map(item => <button key={item} className={tab === item ? 'nav-active' : 'secondary'} onClick={() => { if (item === 'record') setEditing(null); setTab(item); }} disabled={(item === 'record' && !canRecord) || (item === 'review' && !canReview)}>{item.replace('-', ' ')}</button>)}</nav>}{message && <p className="session">{message}<button className="text-button" onClick={() => setMessage('')}>Dismiss</button></p>}{tab === 'dashboard' && <Dashboard summaries={summaries} approved={approved} />}{tab === 'record' && <Record key={editing?.id ?? 'new'} session={session} editing={editing} onCancel={() => { setEditing(null); setTab('my-incidents'); }} onSubmit={submitIncident} />}{tab === 'my-incidents' && <MyIncidents incidents={incidents.filter(x => x.reporter === session?.name && x.hazard === session.hazard && x.ward === session.ward)} onEdit={edit} onDelete={remove} />}{tab === 'review' && <Review incidents={reviewable} canReview={!!canReview} onDecide={decide} />}{tab === 'reports' && <Reports approved={approved} filter={filter} setFilter={setFilter} onExport={exportCsv} />}{tab === 'alerts' && <Alerts alerts={alerts} />}{showSignIn && <SignIn name={name} setName={setName} role={role} setRole={setRole} hazard={assignedHazard} setHazard={setAssignedHazard} ward={ward} setWard={setWard} onSubmit={signIn} onClose={() => setShowSignIn(false)} />}</main>;
}

export function Dashboard({ summaries, approved }: { summaries: Summary[]; approved: Incident[] }) { return <><section className="hero"><p>LIVE OPERATIONS VIEW</p><h2>Approved incidents at a glance</h2><span>Only provincial-approved incidents are visible here, on the map, and in reports.</span></section><section className="cards">{summaries.map(x => <article key={x.name}><i style={{ background: x.color }} /><small>{x.name}</small><strong>{x.count}</strong><span>approved incidents</span></article>)}</section><section className="grid"><article className="panel"><h3>Incident map</h3><div className="map">{approved.length ? approved.map(x => <span key={x.id} className="marker" style={{ left: `${40 + ((x.longitude + 180) / 360) * 45}%`, top: `${20 + ((90 - x.latitude) / 180) * 55}%`, background: colors[x.hazard] }} title={`${x.hazard}: ${x.ward}`} />) : 'No approved markers yet.'}</div></article><article className="panel"><h3>Recent approved incidents</h3>{approved.slice(0, 4).map(x => <p key={x.id}><b>{x.hazard}</b><br /><small>{x.ward} · {x.severity}</small></p>) || <p>No approved incidents yet.</p>}</article></section></> }

export function Record({ session, editing, onCancel, onSubmit }: { session: Session | null; editing: Incident | null; onCancel: () => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { if (!session || session.role !== 'Ward recorder') return <Notice text="Only ward recorders may capture incidents." />; const incident = editing?.hazard === session.hazard ? editing : null; return <section className="panel form-panel"><p>WARD CAPTURE · {session.hazard.toUpperCase()}</p><h2>{incident ? 'Correct and resubmit' : `New ${session.hazard} incident`}</h2><form onSubmit={onSubmit} aria-label="Incident form"><div className="form-grid"><label>Ward<input value={session.ward} disabled /></label><label>District<input name="district" defaultValue={incident?.district} placeholder="District" required /></label><label>Date and time<input name="occurredAt" type="datetime-local" defaultValue={incident?.occurredAt} required /></label><label>Severity<select name="severity" defaultValue={incident?.severity ?? 'LOW'}><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></label><label>Latitude<input name="latitude" type="number" step="any" min="-90" max="90" defaultValue={incident?.latitude} required /></label><label>Longitude<input name="longitude" type="number" step="any" min="-180" max="180" defaultValue={incident?.longitude} required /></label>{indicators[session.hazard].map(([key, label]) => <label key={key}>{label}<input name={key} defaultValue={incident?.fields[key]} required /></label>)}</div><div className="actions-row"><button type="submit">{incident ? 'Save and resubmit' : 'Submit for approval'}</button>{incident && <button type="button" className="secondary" onClick={onCancel}>Cancel</button>}</div></form></section> }

export function Review({ incidents, canReview, onDecide }: { incidents: Incident[]; canReview: boolean; onDecide: (id: string, status: Status, reason: string) => void }) { const [decision, setDecision] = useState<{ id: string; status: Status } | null>(null); const [reason, setReason] = useState(''); if (!canReview) return <Notice text="Only provincial supervisors and administrators can review incidents." />; function open(id: string, status: Status) { setReason(''); setDecision({ id, status }); } function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!decision || !reason.trim()) return; onDecide(decision.id, decision.status, reason); setDecision(null); } return <section className="panel"><p>PROVINCIAL REVIEW QUEUE</p><h2>Pending incidents</h2>{incidents.length ? incidents.map(x => <article className="incident" key={x.id}><div><b>{x.hazard} · {x.severity}</b><p>{x.ward}, {x.district} · reported by {x.reporter}</p><small>{Object.entries(x.fields).map(([k, v]) => `${k}: ${v}`).join(' · ')}</small><details><summary>Audit trail</summary>{x.audit.map(a => <p key={a.at}>{new Date(a.at).toLocaleString()} — {a.actor}: {a.action} {a.reason && `(${a.reason})`}</p>)}</details></div><div className="actions"><button onClick={() => onDecide(x.id, 'APPROVED', 'Approved for publication')}>Approve</button><button className="warning" onClick={() => open(x.id, 'CORRECTION_REQUESTED')}>Request correction</button><button className="danger" onClick={() => open(x.id, 'REJECTED')}>Reject</button></div></article>) : <p>No incidents require your attention.</p>}{decision && <div className="decision-box"><h3>{decision.status === 'REJECTED' ? 'Reject incident' : 'Request correction'}</h3><form onSubmit={submit} aria-label="Decision form"><label>Reason<textarea autoFocus value={reason} onChange={e => setReason(e.target.value)} placeholder="Explain the decision clearly for the recorder" required /></label><div className="actions-row"><button type="submit">Confirm {decision.status === 'REJECTED' ? 'rejection' : 'correction request'}</button><button type="button" className="secondary" onClick={() => setDecision(null)}>Cancel</button></div></form></div>}</section> }

export function MyIncidents({ incidents, onEdit, onDelete }: { incidents: Incident[]; onEdit: (incident: Incident) => void; onDelete: (id: string) => void }) { return <section className="panel"><p>MY SUBMISSIONS</p><h2>Incident status</h2>{incidents.length ? incidents.map(x => <article className="incident" key={x.id}><div><b>{x.hazard} · {x.status}</b><p>{x.ward}, {x.district} · {x.severity}</p><details><summary>Audit trail</summary>{x.audit.map(a => <p key={a.at}>{new Date(a.at).toLocaleString()} — {a.actor}: {a.action} {a.reason && `(${a.reason})`}</p>)}</details></div><div className="actions"><span className="status">{x.status.replace('_', ' ')}</span>{(x.status === 'PENDING' || x.status === 'CORRECTION_REQUESTED') && <button className="secondary" onClick={() => onEdit(x)}>Edit</button>}{x.status === 'PENDING' && <button className="danger" onClick={() => onDelete(x.id)}>Delete</button>}</div></article>) : <p>You have not submitted any incidents.</p>}</section> }

export function Reports({ approved, filter, setFilter, onExport }: { approved: Incident[]; filter: Hazard | 'All'; setFilter: (h: Hazard | 'All') => void; onExport: () => void }) { const visible = approved.filter(x => filter === 'All' || x.hazard === filter); return <section className="panel"><p>APPROVED DATA EXPORT</p><h2>Reports</h2><label>Hazard filter<select value={filter} onChange={e => setFilter(e.target.value as Hazard | 'All')}><option>All</option>{hazards.map(h => <option key={h}>{h}</option>)}</select></label><p>{visible.length} approved incident(s) match this filter.</p><button onClick={onExport} disabled={!visible.length}>Download CSV</button><p><small>PDF, DOCX, and XLSX exports are represented by report-service and are the next backend integration point.</small></p></section> }

export function Alerts({ alerts }: { alerts: Incident[] }) { return <section className="panel"><p>ASYNC ALERT LOG</p><h2>Alert candidates</h2>{alerts.length ? alerts.map(x => <article className="incident" key={x.id}><div><b>{x.hazard} alert</b><p>{x.ward} · {x.severity}</p></div><span className="status">Queued for email and WhatsApp</span></article>) : <p>No approved incidents meet the configured alert criteria.</p>}<p><small>In production, alert-service receives these events through RabbitMQ and records delivery status by recipient and channel.</small></p></section> }

export function Notice({ text }: { text: string }) { return <section className="panel"><h2>Access restricted</h2><p>{text}</p></section> }

export function SignIn(props: { name: string; setName: (v: string) => void; role: Role; setRole: (v: Role) => void; hazard: Hazard; setHazard: (v: Hazard) => void; ward: string; setWard: (v: string) => void; onSubmit: (e: FormEvent<HTMLFormElement>) => void; onClose: () => void }) { return <div className="backdrop" role="presentation"><form role="dialog" className="dialog" onSubmit={props.onSubmit} aria-label="Sign in"><button type="button" className="close" onClick={props.onClose} aria-label="Close">×</button><p>DEVELOPMENT ACCESS</p><h2>Sign in to DPDMS</h2><label>Name<input autoFocus value={props.name} onChange={e => props.setName(e.target.value)} placeholder="Your name" required /></label><label>Role<select value={props.role} onChange={e => props.setRole(e.target.value as Role)}>{['Ward recorder', 'Provincial supervisor', 'Provincial administrator', 'National viewer'].map(x => <option key={x}>{x}</option>)}</select></label><label>Assigned hazard<select value={props.hazard} onChange={e => props.setHazard(e.target.value as Hazard)}>{hazards.map(x => <option key={x}>{x}</option>)}</select></label>{props.role === 'Ward recorder' && <label>Assigned ward<input value={props.ward} onChange={e => props.setWard(e.target.value)} required /></label>}<button type="submit">Continue</button><small>Development-only local session. Production authentication belongs in auth-service.</small></form></div> }
